export const prismLanguageList = [
    'javascript', 'typescript',
    'css', 'css-extras', 'html', 'less', 'sass', 'scss',
    'svg', 'icon',
    'markup',
    'http', 'uri', 'url',
    'c', 'cpp', 'cmake', 'objc',
    'rust',
    'go',
    'php', 'phpdoc',
    'perl',
    'java', 'javadoc', 'groovy', 'kotlin', 'kt', 'kts', 'scala',
    'latex', 'tex', 'matlab',
    'sql', 'graphql', 'mongodb',
    'erlang',
    'lua',
    'python', 'py', 'django', 'jinja2',
    'csharp', 'dotnet',
    'cobol',
    'makefile',
    'json', 'json5', 'jsonp',
    'xml', 'yaml', 'yml', 'ini', 'toml',
    'bash', 'shell', 'batch',
    'docker', 'dockerfile',
    'git',
    'vim',
    'dns-zone',
    'log',
    'qml',
    'scheme',
    'swift'
].sort()